version: '3'

services:
  app-server:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_PORT=5000
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - backend
      - frontend

  db:
    image: 'postgres:14.4-alpine'
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - backend

  app-client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map the exposed port 80 on the container to port 9090 on the host machine
    depends_on:
      - app-server
    networks:
      - frontend

volumes:
  db-data:

networks:
  backend:
  frontend: