spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
document:
  bucket-name: awspartierbucket
cloud:
  aws:
    region:
      static: eu-central-1
      auto: false
    credentials:
      access-key: AKIASAEW4Z3PZ3PXOBH4
      secret-key: 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